perl add_vari.pl cn_abbAyi.p > mn_abbAyi.p
perl add_vari.pl cn_bAludu.p > mn_bAludu.p
perl add_vari.pl cn_baMdi.p > mn_baMdi.p
perl add_vari.pl cn_beVMdu.p > mn_beVMdu.p
perl add_vari.pl cn_bonu.p > mn_bonu.p
perl add_vari.pl cn_buddi.p > mn_buddi.p
perl add_vari.pl cn_cenu.p > mn_cenu.p
perl add_vari.pl cn_cillu.p > mn_cillu.p
perl add_vari.pl cn_eVnimixi.p > mn_eVnimixi.p
perl add_vari.pl cn_gaxi.p > mn_gaxi.p
perl add_vari.pl cn_goru.p > mn_goru.p
perl add_vari.pl cn_goyi.p > mn_goyi.p
perl add_vari.pl cn_guddu.p > mn_guddu.p
perl add_vari.pl cn_gudi.p > mn_gudi.p
perl add_vari.pl cn_gUdu.p > mn_gUdu.p
perl add_vari.pl cn_guMdu.p > mn_guMdu.p
perl add_vari.pl cn_illu.p > mn_illu.p
perl add_vari.pl cn_kalcar.p > mn_kalcar.p
perl add_vari.pl cn_kannu.p > mn_kannu.p
perl add_vari.pl cn_kIlu.p > mn_kIlu.p
perl add_vari.pl cn_kota.p > mn_kota.p
perl add_vari.pl cn_koti.p > mn_koti.p
perl add_vari.pl cn_kotu.p > mn_kotu.p
perl add_vari.pl cn_koVttu.p > mn_koVttu.p
perl add_vari.pl cn_kuMxelu.p > mn_kuMxelu.p
perl add_vari.pl cn_maMxi.p > mn_maMxi.p
perl add_vari.pl cn_maniRi.p > mn_maniRi.p
perl add_vari.pl cn_meku.p > mn_meku.p
perl add_vari.pl cn_meVxadu.p > mn_meVxadu.p
perl add_vari.pl cn_nOkaru.p > mn_nOkaru.p
perl add_vari.pl cn_pAlu.p > mn_pAlu.p
perl add_vari.pl cn_paMxeVM.p > mn_paMxeVM.p
perl add_vari.pl cn_paMxiri.p > mn_paMxiri.p
perl add_vari.pl cn_pani.p > mn_pani.p
perl add_vari.pl cn_peVnnu.p > mn_peVnnu.p
perl add_vari.pl cn_peVtteV.p > mn_peVtteV.p
perl add_vari.pl cn_pillavAdu.p > mn_pillavAdu.p
perl add_vari.pl cn_piMdi.p > mn_piMdi.p
perl add_vari.pl cn_puli.p > mn_puli.p
perl add_vari.pl cn_putti.p > mn_putti.p
perl add_vari.pl cn_pUvu.p > mn_pUvu.p
perl add_vari.pl cn_rANi.p > mn_rANi.p
perl add_vari.pl cn_rAwri.p > mn_rAwri.p
perl add_vari.pl cn_rikRA.p > mn_rikRA.p
perl add_vari.pl cn_snehiwudu.p > mn_snehiwudu.p
perl add_vari.pl cn_Uru.p > mn_Uru.p
perl add_vari.pl cn_velu.p > mn_velu.p
perl add_vari.pl cn_veVyyi.p > mn_veVyyi.p
perl add_vari.pl cn_wiragali.p > mn_wiragali.p
perl add_vari.pl cn_xAri.p > mn_xAri.p
perl add_vari.pl cn_xrAyi.p > mn_xrAyi.p
